### ISSUE TITLE
无法订阅行情

### ISSUE THREAD

**Issue by xzc8** [RationalityFrontline/jctp#1]
行情接口可以登录，订阅行情显示成功，使用Wireshark查看网络连接可以发现程序已经和CTP系统建立连接，但是程序出的结果如下

`On Front Connected
Brokerid[，登陆成功,0]
订阅成功
交易日20210719
OnRspError: 09
OnRspError: 825378377`

与使用手册相比可以发现订阅行情方法SubscribeMarketData的输入参数缺少一个整形参数。

这是jar包中的调用JNI底层函数的代码，此处缺少一个整形输入参数。
` public int SubscribeMarketData(String[] ppInstrumentID) {
    return jctpJNI.CThostFtdcMdApi_SubscribeMarketData(swigCPtr, this, ppInstrumentID);
  }
`

请问我的问题是因为这个整形参数吗？还是因为我设置不正确？

**Comment by RationalityFrontline** [comment]
这个行情订阅是没问题的，我测试过很多次的，可能是你订阅的合约代码有问题。与那个缺少的整型参数无关，那个整型是你订阅的合约数组的长度，因为 C++ 里的数组只是一个指针，没有长度信息，但 Java 里的数组是有长度信息的，所以 Java 封装后省略了这个参数。
我不清楚你是如何请求订阅的，也不清楚你请求订阅后的结果是什么，你描述的有点模糊不清。
完整的登录流程：
`Init -> OnFrontConnected -> ReqUserLogin -> OnRspUserLogin`
完成上面的流程后才可以订阅行情：
`SubscribeMarketData -> OnRspSubMarketData`
如果出错，你可以打印回调函数中的参数 pRspInfo 的字段 errorMsg 来看报错信息。
请描述清楚你那边出现的结果是什么，是哪个回调函数里报错，pRspInfo.errorID 和 pRspInfo.errorMsg 又是什么值。
如果是没有 Tick 推送（OnRtnDepthMarketData 没有回调），请检查合约代码是否正确、是否处于交易时间段。
合约代码示例："m2109" -> 豆粕2109

**Comment by RationalityFrontline** [comment]
这个行情订阅是没问题的，我测试过很多次的，可能是你订阅的合约代码有问题。与那个缺少的整型参数无关，那个整型是你订阅的合约数组的长度，因为 C++ 里的数组只是一个指针，没有长度信息，但 Java 里的数组是有长度信息的，所以 Java 封装后省略了这个参数。
我不清楚你是如何请求订阅的，也不清楚你请求订阅后的结果是什么，你描述的有点模糊不清。
完整的登录流程：
`Init -> OnFrontConnected -> ReqUserLogin -> OnRspUserLogin`
完成上面的流程后才可以订阅行情：
`SubscribeMarketData -> OnRspSubMarketData`
如果出错，你可以打印回调函数中的参数 pRspInfo 的字段 errorMsg 来看报错信息。
请描述清楚你那边出现的结果是什么，是哪个回调函数里报错，pRspInfo.errorID 和 pRspInfo.errorMsg 又是什么值。
如果是没有 Tick 推送（OnRtnDepthMarketData 没有回调），请检查合约代码是否正确、是否处于交易时间段。
合约代码示例："m2109" -> 豆粕2109

**Comment by xzc8** [comment]
谢谢解答，经过排查发现是我的登录流程不对，此接口可以正常使用，十分感谢。
